# __Importing the Data__
Import the root dataset from directory (which came from the NADAC repository) and bring it up to date by appending new data to this file, and export it for use in future modules.

In [1]:
import pandas as pd
from sodapy import Socrata

In [3]:
# Import most current data from the API
# a4y5-998d --> Weekly data back to February 2013 (the request timed out when I used this endpoint - maybe because the dataset was so big?)
# rt4v-78r4 --> Weekly data back to May 2018

client = Socrata('data.medicaid.gov', app_token='APP_TOKEN', username='USERNAME', password = 'PASSWORD')
results = client.get('rt4v-78r4', limit = 100000)
client.close()
recent_prices = pd.DataFrame.from_records(results)

In [2]:
#------------------------#
# FOR USE AFTER DOWNLOAD #
#------------------------#

price_root_data = pd.read_csv('NADAC_Source_Data.csv', encoding='utf-8')

# Or download it from the URL (slower - 5 minutes?)
# price_root_data = pd.read_csv('https://data.medicaid.gov/api/views/a4y5-998d/rows.csv?accessType=DOWNLOAD') # The file is almost 700MB, so it can take some time to download
# price_root_data.info()

Now we'll collect new data from the API, concatenate it to our root data source (the file we just imported), and save it back to the original file.

In [4]:
# Reformat the price_root_data columns so the names match the recent_prices
price_root_data.columns = price_root_data.columns.str.replace(' ', '_').str.lower()

# Concatenate current data with price_root_data
all_price_data = pd.concat([price_root_data, recent_prices], ignore_index = True, sort = True)
# Drop duplicate rows
all_price_data.drop_duplicates(inplace = True)

In [5]:
all_price_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7347443 entries, 0 to 7347442
Data columns (total 12 columns):
as_of_date                                   object
classification_for_rate_setting              object
corresponding_generic_drug_effective_date    object
corresponding_generic_drug_nadac_per_unit    object
effective_date                               object
explanation_code                             object
nadac_per_unit                               object
ndc                                          object
ndc_description                              object
otc                                          object
pharmacy_type_indicator                      object
pricing_unit                                 object
dtypes: object(12)
memory usage: 728.7+ MB

In [6]:
# Checking head and tail of the dataframe for a visual check that data types are lining up as expected
all_price_data.head()

,as_of_date,classification_for_rate_setting,corresponding_generic_drug_effective_date,corresponding_generic_drug_nadac_per_unit,effective_date,explanation_code,nadac_per_unit,ndc,ndc_description,otc,pharmacy_type_indicator,pricing_unit
0,09/18/2019,G,NaN,NaN,09/18/2019,1,0.31284,113005452,12-HR DECONGEST 120 MG CAPLET,Y,C/I,EA
1,09/18/2019,G,NaN,NaN,09/18/2019,1,0.31284,36800005452,12-HR DECONGEST 120 MG CAPLET,Y,C/I,EA
2,09/18/2019,G,NaN,NaN,09/18/2019,1,0.31284,36800005460,12-HR DECONGEST 120 MG CAPLET,Y,C/I,EA
3,09/18/2019,G,NaN,NaN,09/18/2019,1,0.31284,24385005452,12HR NASAL DECONGEST ER 120 MG,Y,C/I,EA
4,09/18/2019,G,NaN,NaN,09/18/2019,1,0.31284,70000016401,12HR NASAL DECONGEST ER 120 MG,Y,C/I,EA

In [7]:
all_price_data.tail()

,as_of_date,classification_for_rate_setting,corresponding_generic_drug_effective_date,corresponding_generic_drug_nadac_per_unit,effective_date,explanation_code,nadac_per_unit,ndc,ndc_description,otc,pharmacy_type_indicator,pricing_unit
7347438,2019-05-15T00:00:00.000,B,NaN,NaN,2019-01-01T00:00:00.000,2,8.30666,54123095730,ZUBSOLV 5.7-1.4 MG TABLET SL,N,C/I,EA
7347439,2019-05-15T00:00:00.000,B,NaN,NaN,2019-01-01T00:00:00.000,2,12.40266,54123098630,ZUBSOLV 8.6-2.1 MG TABLET SL,N,C/I,EA
7347440,2019-05-15T00:00:00.000,B,NaN,NaN,2019-01-18T00:00:00.000,"2, 5",47.61993,24208035805,ZYLET EYE DROPS,N,C/I,ML
7347441,2019-05-15T00:00:00.000,B,2019-04-17T00:00:00.000,0.23226,2019-02-19T00:00:00.000,4,40.4315,00002442030,ZYPREXA 20 MG TABLET,N,C/I,EA
7347442,2019-05-15T00:00:00.000,B,NaN,NaN,2019-01-10T00:00:00.000,4,87.62544,57894015012,ZYTIGA 250 MG TABLET,N,C/I,EA

In [9]:
from urllib.request import urlopen # Used to pull the zip file from the site
import os                          # Used to get the current working directory (for data folder)
from zipfile import ZipFile        # Used to unzip the file
from io import BytesIO             # Writes the file to RAM (temporary)
import pandas as pd
import datetime as dt

In [31]:
# Save/Export the new all_price_data dataframe
current_dir = os.getcwd()
data_dir = current_dir + '\data'

#Check if the path doesn't already exist, and create a new 'data' directory if it doesn't
if not os.path.exists(current_dir):
    os.makedirs(data_dir)
print(data_dir)

# Save/Export the new all_price_data dataframe
all_price_data.to_csv('data/NADAC_Current_Data.csv')
print("File saved!")

C:\Users\The Fat Lady\Documents\Python Code\TDI\DrugPricePredictor/data
File saved!

# __Patent Datasets__

Because this dataset comes in three parts, some slight modifications may be necessary prior to merging here.  Code in other notebooks aims to merge this data with the price data.

In [30]:
# Request the file to be downloaded
current_dir = os.getcwd()
data_dir = current_dir + '\data'
zipurl = 'https://www.fda.gov/media/76860/download'

#Check if the path doesn't already exist, and create a new 'data' directory if it doesn't
if not os.path.exists(current_dir):
    os.makedirs(data_dir)

# Download and unzip the patent datasets 
with urlopen(zipurl) as zipresp:
    with ZipFile(BytesIO(zipresp.read())) as zfile:
        zfile.extractall(data_dir)

In [13]:
# Read in relevant files (the first 3 belong in a set and will be combined shortly)
drugs = pd.read_csv('data/products.txt', sep='~', engine='python')
patents = pd.read_csv('data/patent.txt', sep='~')
exclusivity = pd.read_csv('data/exclusivity.txt', sep='~')

## __Drugs Dataframe Investigation__

In [15]:
drugs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37702 entries, 0 to 37701
Data columns (total 14 columns):
Ingredient             37702 non-null object
DF;Route               37702 non-null object
Trade_Name             37702 non-null object
Applicant              37702 non-null object
Strength               37635 non-null object
Appl_Type              37702 non-null object
Appl_No                37702 non-null int64
Product_No             37702 non-null int64
TE_Code                17993 non-null object
Approval_Date          37702 non-null object
RLD                    37702 non-null object
RS                     37702 non-null object
Type                   37702 non-null object
Applicant_Full_Name    37702 non-null object
dtypes: int64(2), object(12)
memory usage: 4.0+ MB

In [14]:
drugs.head()

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type,Appl_No,Product_No,TE_Code,Approval_Date,RLD,RS,Type,Applicant_Full_Name
0,BUDESONIDE,"AEROSOL, FOAM;RECTAL",UCERIS,VALEANT PHARMS INTL,2MG/ACTUATION,N,205613,1,NaN,"Oct 7, 2014",Yes,Yes,RX,VALEANT PHARMACEUTICALS INTERNATIONAL
1,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,PERRIGO UK FINCO,0.12%,A,78337,1,AB,"Nov 26, 2012",No,No,RX,PERRIGO UK FINCO LTD PARTNERSHIP
2,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,RICONPHARMA LLC,0.12%,A,207144,1,AB,"May 24, 2017",No,No,RX,RICONPHARMA LLC
3,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,TARO,0.12%,A,208204,1,AB,"May 24, 2017",No,No,RX,TARO PHARMACEUTICAL INDUSTRIES LTD
4,CLINDAMYCIN PHOSPHATE,"AEROSOL, FOAM;TOPICAL",CLINDAMYCIN PHOSPHATE,PERRIGO UK FINCO,1%,A,90785,1,AT,"Mar 31, 2010",No,No,RX,PERRIGO UK FINCO LTD PARTNERSHIP

This appears to be an almost entirely complete dataset (with the exception of the 'Strength' and 'TE_Code' columns)!  Let's take a look at the number of unique values in each column (including the NaNs).

In [16]:
drugs['Appl_No'].value_counts(dropna=False)

19630     53
19631     16
4056      15
21703     15
17512     15
62814     14
204824    14
20533     13
20280     13
76187     12
18268     12
206977    12
21402     12
210831    12
209713    12
11719     12
20678     12
21924     12
20734     12
21137     12
21301     12
21210     12
21292     12
552       12
9218      12
21116     12
20616     12
21342     12
21540     11
76752     11
          ..
84557      1
87294      1
18522      1
20569      1
9000       1
84026      1
88120      1
75830      1
84329      1
71728      1
90143      1
18458      1
88088      1
204823     1
77845      1
72162      1
61453      1
84674      1
86610      1
6441       1
200691     1
204785     1
202736     1
83930      1
88024      1
206314     1
75734      1
78921      1
20411      1
71683      1
Name: Appl_No, Length: 22084, dtype: int64

In [17]:
# Interesting that there are 53 drugs with the same application number (Appl_No).  What are they? They do have different strengths, so we'll leave them alone as they're not true duplicates
drugs[drugs['Appl_No']==19630].head(10)

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type,Appl_No,Product_No,TE_Code,Approval_Date,RLD,RS,Type,Applicant_Full_Name
12292,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 10% AND ...,B BRAUN,10GM/100ML;37MG/100ML;200MG/100ML,N,19630,31,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12293,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 10% AND ...,B BRAUN,10GM/100ML;37MG/100ML;450MG/100ML,N,19630,37,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12294,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 10% AND ...,B BRAUN,10GM/100ML;37MG/100ML;900MG/100ML,N,19630,43,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12295,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 5% AND S...,B BRAUN,5GM/100ML;37MG/100ML;110MG/100ML,N,19630,1,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12296,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 5% AND S...,B BRAUN,5GM/100ML;37MG/100ML;200MG/100ML,N,19630,7,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12297,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 5% AND S...,B BRAUN,5GM/100ML;37MG/100ML;330MG/100ML,N,19630,13,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12298,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 5% AND S...,B BRAUN,5GM/100ML;37MG/100ML;450MG/100ML,N,19630,19,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12299,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.037% IN DEXTROSE 5% AND S...,B BRAUN,5GM/100ML;37MG/100ML;900MG/100ML,N,19630,25,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12302,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.075% IN DEXTROSE 10% AND ...,B BRAUN,10GM/100ML;75MG/100ML;200MG/100ML,N,19630,32,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC
12303,DEXTROSE; POTASSIUM CHLORIDE; SODIUM CHLORIDE,INJECTABLE;INJECTION,POTASSIUM CHLORIDE 0.075% IN DEXTROSE 10% AND ...,B BRAUN,10GM/100ML;75MG/100ML;450MG/100ML,N,19630,38,NaN,"Feb 17, 1988",No,No,RX,B BRAUN MEDICAL INC

## __Exclusivity Data Investigation__

In [19]:
exclusivity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1866 entries, 0 to 1865
Data columns (total 5 columns):
Appl_Type           1866 non-null object
Appl_No             1866 non-null int64
Product_No          1866 non-null int64
Exclusivity_Code    1866 non-null object
Exclusivity_Date    1866 non-null object
dtypes: int64(2), object(3)
memory usage: 73.0+ KB

In [18]:
exclusivity.head()

  Appl_Type  Appl_No  Product_No Exclusivity_Code Exclusivity_Date
0         N     9190           1           ODE-64      Apr 4, 2021
1         N    11366           2           ODE-96      Aug 7, 2022
2         N    17858           1           ODE-29     Aug 13, 2019
3         N    20287          11              NPP     May 16, 2022
4         N    20287          10              NPP     May 16, 2022

## __Patents Dataframe Investigation__

In [21]:
patents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14717 entries, 0 to 14716
Data columns (total 10 columns):
Appl_Type                  14717 non-null object
Appl_No                    14717 non-null int64
Product_No                 14717 non-null int64
Patent_No                  14717 non-null object
Patent_Expire_Date_Text    14717 non-null object
Drug_Substance_Flag        2529 non-null object
Drug_Product_Flag          8019 non-null object
Patent_Use_Code            7910 non-null object
Delist_Flag                73 non-null object
Submission_Date            10407 non-null object
dtypes: int64(2), object(8)
memory usage: 1.1+ MB

In [20]:
patents.head()

,Appl_Type,Appl_No,Product_No,Patent_No,Patent_Expire_Date_Text,Drug_Substance_Flag,Drug_Product_Flag,Patent_Use_Code,Delist_Flag,Submission_Date
0,N,20571,1,6403569,"Apr 28, 2020",NaN,NaN,U-449,NaN,NaN
1,N,20571,2,6403569,"Apr 28, 2020",NaN,NaN,U-449,NaN,NaN
2,N,20610,1,7625884,"Aug 24, 2026",NaN,NaN,U-141,NaN,NaN
3,N,20629,1,6579981,"Jun 17, 2020",NaN,NaN,U-501,NaN,NaN
4,N,20685,1,6689761,"Feb 10, 2021",NaN,NaN,U-554,NaN,NaN

-------------------------------------------------------

**Note:** Each drug application receives a number ('Appl_No').   An application may have many drugs on it, so each of these drugs on an application receive a product number ('Product_No').  Therefore, I can match up the drugs in the exculusitity and patent data files with those in the drugs data file by first comparing application numbers in each, and the secondarily confirming their product numbers.

-------------------------------------------------------

In [22]:
exclusivity_indexed=exclusivity.set_index(['Appl_No', 'Product_No'])
exclusivity_indexed

                   Appl_Type Exclusivity_Code Exclusivity_Date
Appl_No Product_No
9190    1                  N           ODE-64      Apr 4, 2021
11366   2                  N           ODE-96      Aug 7, 2022
17858   1                  N           ODE-29     Aug 13, 2019
20287   11                 N              NPP     May 16, 2022
        10                 N              NPP     May 16, 2022
        9                  N              NPP     May 16, 2022
        8                  N              NPP     May 16, 2022
        7                  N              NPP     May 16, 2022
        6                  N              NPP     May 16, 2022
        5                  N              NPP     May 16, 2022
        4                  N              NPP     May 16, 2022
        3                  N              NPP     May 16, 2022
        2                  N              NPP     May 16, 2022
        1                  N              NPP     May 16, 2022
20351   2                  N            I-752      Apr 5, 2020
20380   2                  N              RTO      Jul 8, 2019
20702   2                  N            M-204     Jun 23, 2020
        1                  N            M-204     Jun 23, 2020
20725   5                  N             M-93     Jul 29, 2019
        4                  N             M-93     Jul 29, 2019
20808   2                  N            I-752      Apr 5, 2020
19599   2                  N            M-191     Nov 10, 2019
20965   1                  N            I-766      Mar 9, 2021
21908   2                  N            M-225     Apr 26, 2021
        1                  N            M-225     Apr 26, 2021
21923   1                  N           ODE-56     Nov 22, 2020
21928   2                  N            M-192     Dec 16, 2019
        2                  N            M-183     Aug 12, 2019
        2                  N            M-237     Feb 22, 2022
        1                  N            M-192     Dec 16, 2019
...                      ...              ...              ...
206143  2                  N              PED     Oct 15, 2020
        1                  N              PED     Oct 15, 2020
208694  1                  N              PED     Nov 30, 2020
210709  1                  N              PED     May 14, 2021
209501  3                  N              PED     Apr 11, 2021
        2                  N              PED     Apr 11, 2021
        1                  N              PED     Apr 11, 2021
209964  1                  N              PED     Oct 22, 2026
        1                  N              PED     Oct 22, 2022
        1                  N              PED     Oct 15, 2020
21883   1                  N             GAIN     May 23, 2024
205436  1                  N             GAIN     Jun 20, 2024
205435  1                  N             GAIN     Jun 20, 2024
206829  1                  N             GAIN     Dec 19, 2024
206334  1                  N             GAIN      Aug 6, 2024
207500  1                  N             GAIN      Mar 6, 2027
207501  1                  N             GAIN      Mar 6, 2027
207500  1                  N             GAIN      Mar 6, 2025
207501  1                  N             GAIN      Mar 6, 2025
208611  1                  N             GAIN     Jun 19, 2027
208610  1                  N             GAIN     Jun 19, 2027
210303  1                  N             GAIN     Jun 25, 2028
211109  1                  N             GAIN     Aug 27, 2028
209363  1                  N             GAIN     Sep 15, 2027
209816  1                  N             GAIN      Oct 2, 2028
209817  1                  N             GAIN      Oct 2, 2028
207356  1                  N             GAIN     Sep 28, 2030
212862  1                  N             GAIN     Aug 14, 2029
211673  1                  N             GAIN     Aug 19, 2029
211672  1                  N             GAIN     Aug 19, 2029

[1866 rows x 3 columns]

### __Merging Patent-related Datasets__

In [23]:
# Merged with 'left' because there were some nan patent data that was unneeded
all_patent_data = pd.merge(drugs, patents, on = ['Appl_No', 'Product_No'], how = 'left')
# all_patent_data.head()

In [25]:
# Merge in the data from exclusivity.txt
all_patent_data = pd.merge(all_patent_data, exclusivity, on=['Appl_No', 'Product_No'], how='left')
all_patent_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59716 entries, 0 to 59715
Data columns (total 25 columns):
Ingredient                 59716 non-null object
DF;Route                   59716 non-null object
Trade_Name                 59716 non-null object
Applicant                  59716 non-null object
Strength                   59648 non-null object
Appl_Type_x                59716 non-null object
Appl_No                    59716 non-null int64
Product_No                 59716 non-null int64
TE_Code                    20659 non-null object
Approval_Date              59716 non-null object
RLD                        59716 non-null object
RS                         59716 non-null object
Type                       59716 non-null object
Applicant_Full_Name        59716 non-null object
Appl_Type_y                24230 non-null object
Patent_No                  24230 non-null object
Patent_Expire_Date_Text    24230 non-null object
Drug_Substance_Flag        5010 non-null object
Drug_Product_Flag          11689 non-null object
Patent_Use_Code            13789 non-null object
Delist_Flag                86 non-null object
Submission_Date            17324 non-null object
Appl_Type                  17087 non-null object
Exclusivity_Code           17087 non-null object
Exclusivity_Date           17087 non-null object
dtypes: int64(2), object(23)
memory usage: 11.8+ MB

In [26]:
all_patent_data.head()

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type_x,Appl_No,Product_No,TE_Code,Approval_Date,...,Patent_No,Patent_Expire_Date_Text,Drug_Substance_Flag,Drug_Product_Flag,Patent_Use_Code,Delist_Flag,Submission_Date,Appl_Type,Exclusivity_Code,Exclusivity_Date
0,BUDESONIDE,"AEROSOL, FOAM;RECTAL",UCERIS,VALEANT PHARMS INTL,2MG/ACTUATION,N,205613,1,NaN,"Oct 7, 2014",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,PERRIGO UK FINCO,0.12%,A,78337,1,AB,"Nov 26, 2012",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,RICONPHARMA LLC,0.12%,A,207144,1,AB,"May 24, 2017",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BETAMETHASONE VALERATE,"AEROSOL, FOAM;TOPICAL",BETAMETHASONE VALERATE,TARO,0.12%,A,208204,1,AB,"May 24, 2017",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CLINDAMYCIN PHOSPHATE,"AEROSOL, FOAM;TOPICAL",CLINDAMYCIN PHOSPHATE,PERRIGO UK FINCO,1%,A,90785,1,AT,"Mar 31, 2010",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# Save/Export the new all_patent_data dataframe
current_dir = os.getcwd()
data_dir = current_dir + '\data'

#Check if the path doesn't already exist, and create a new 'data' directory if it doesn't
if not os.path.exists(current_dir):
    os.makedirs(data_dir)
print(data_dir)

# Save/Export the new patent_data dataframe
all_patent_data.to_csv('data/patent_data.csv')
print("File saved!")

C:\Users\The Fat Lady\Documents\Python Code\TDI\DrugPricePredictor\data
File saved!